### ISSUE TITLE
2015/08/08 OSC Kyoto にブース出展

### ISSUE THREAD

**Issue by dynamis** [fxosorg/events#10]
Mozilla で講演＆ブース出展します。Firefox OS 端末 (Fx0) 展示するので関西圏のヘルプ募集。

http://www.ospn.jp/osc2015-kyoto/

**Comment by uenoshin** [comment]
ヘルプ行けますー

**Comment by dynamis** [comment]
[プレゼン by dynamis](https://www.ospn.jp/osc2015-kyoto/modules/eguide/event.php?eid=61): FirefoxとWebの未来 - Mozillaはこれから何にフォーカスしていくのか

[展示ブース by Firefox OS コミュニティ](http://www.ospn.jp/osc2015-kyoto/modules/article/article.php?articleid=1): KDDIより発売中のFirefox OS搭載スマートフォン「Fx0」の実機を自由に触っていただける他、 FirefoxやFirefox OSに関わるご質問なども受け付けていますので、ぜひお気軽にお立ち寄りください。 ＜土曜日のみ出展＞

**Comment by dynamis** [comment]
気づいたら机が特別扱いで 2 テーブル分用意されていました。今のところ以下の展示内容を想定しているのですが、過不足ツッコミとかもう一人くらい現地スタッフさんとか欲しい感じです。
- Fx0
- CHIRIMEN 一式
- FxOS 2.5 デモ (Flame)
- 既存のコミケ本、チラシなど
- 開発環境として WebIDE 見せたりビデオ見せたりする Mac

**Comment by Uemmra3** [comment]
あさいさんの話しを聞きに行きますノシ

上野さんからブーススタッフ募集かけてもらってます。
OWBハンズオン準備会の小菅さんが確定していますし、ほかにも打診中です。

**Comment by dynamis** [comment]
3 人いればどうにかブースはできるし、小菅さんもで計4名になるなら比較的楽ですね。

CHIRIMEN 一式についてはメインのデモセットは同日空いてなくて、ボクの方で別途動くものを明日明後日で準備できる範囲で持って行きますが何かのトラブルで上手く動かなくても勘弁してください。(^^;

**Comment by dynamis** [comment]
memo: chirimen サンプルコード集 https://github.com/MozOpenHard/examples

**Comment by uenoshin** [comment]
関西でアプリハンズオンやった時に登壇してくれた飯田さんもスタッフやってくれるとのことでした。
これで計5人になります。

chirimenの実物はまだ見た事がないので期待してます！

**Comment by dynamis** [comment]
5 人も集まってくださるとは大変心強いです。机 2 つあるけど適度にローテーションしながら安心してやれそうですね。(・・).

CHRIMEN の展示に必要なパーツ類は揃ったので明日の朝セットアップして手持ちで持って行きます。期待を裏切らないように頑張ります。(^^;

あと、KDDI からは以下の支援が届くことになりました。ありがとう〜
- 石郷岡さん
- Fx0 5台 （SIM有）
- Fx0チラシ 300部
- Fx0説明パネル

**Comment by Uemmra3** [comment]
Oh, 人的支援!!
前々日になってアレなのですが、みなさんTシャツとかあるのでしょうか？私はabc2014sの時の紺地のTシャツがありますが・・・。

**Comment by dynamis** [comment]
おおぉ。GET FIREFOX の T シャツなら手持ちで持って行くので、T シャツないひとの数教えてください！
