### ISSUE TITLE
7/27 関東 Firefox OS 勉強会 12th

### ISSUE THREAD

**Issue by albatrosary** [fxosorg/events#15]
doorkeeper:
https://firefox-os.doorkeeper.jp/events/28397

当日スタッフ:
藪下、Hiratori、佐川

**Comment by dynamis** [comment]
司会: chiko
登壇者: dyna, chiko, sakamaki

**Comment by dynamis** [comment]
懇親会手配: 佐川
HTML5 Experts レポート記事執筆: 佐川？

**Comment by dynamis** [comment]
DONE!
