### ISSUE TITLE
[9/11] 関東 Firefox OS 勉強会 13th

### ISSUE THREAD

**Issue by dynamis** [fxosorg/events#17]
メイントピックは FxOS のアドオンかなー？

関連ドキュメントとかは https://github.com/mozilla-japan/firefox-os-community/wiki/seminar-plan

**Comment by mhidaka** [comment]
担当者どなたさまでしたっけ。

**Comment by dynamis** [comment]
すみません放置してました。アドオンで Firefox OS のデザインを変える方法を教えて試してもらうような小規模ハンズオン＠オフィスで計画調整中。僕が勝手に好き勝手なことしちゃうぞモードなので dynamis 担当で。

**Comment by dynamis** [comment]
-  9/11 (金) 19:30 - 21:30 + 懇親会？
  - 8/28 (金) 簡単にターゲティングして告知、psd などのコンテンツ用意でき次第 ML などに拡散
- デザイナー 20 人、開発者 20 人 (別枠募集)
- アドオンでできること 20 分 - Kechol
- デザインできる全体像 10 分 - tommmmy
- 時計ハンズオン説明 20 分 - Miroc & Jecy
- ハンズオンタイム - all

**Comment by dynamis** [comment]
すみません。シュミレータでは良いけど実機で (System Apps 等除いて) ちゃんとアドオンが動作しない問題がいつまでも解決しなくてちゃんとしたアドオン勉強会が開けない状況なので一旦 close させてください

https://bugzilla.mozilla.org/show_bug.cgi?id=1179536
