### ISSUE TITLE
2015/08/22のOSC島根での備品手配リスト

### ISSUE THREAD

**Issue by gurezo** [fxosorg/events#20]
| No | 備品名 | 個数 | 手配先 | 備考 |
| --- | --- | --- | --- | --- |
| 1 | 紙袋 | 150 | Mozilla Japan | Firefox      　 |
| 2 | チラシ | 150 | Mozilla Japan | Firefox OS |
| 3 | チラシ | 150 | Mozilla Japan | CHIRIMEN |
| 4 | シール | 150 | Mozilla Japan | Firefox OS |
| 5 | ふぉくすけ | 2 | Mozilla Japan ，グンマー |  |
| 6 | Flame | 5 | Mozilla Japan |  |
| 7 | セキュリティシール | 10 | Mozilla Japan | 必要？ |
| 8 | 薄い本 | 5 | Mozilla Japan ，グンマー |  |
| 9 | イーゼル | 2 | グンマー | 薄い本用 |
| 10 | 養生テープ | 5 | グンマー |  |
| 11 | スマホスタンド | 3 | グンマー |  |
| 12 | 充電ケーブル | 4 | グンマー |  |
| 13 | 電源タップ | 3 | Mozilla Japan |  |
| 14 | ドライバーセット | 2 | グンマー | 精密ドライバも含む |
| 15 | サインペン | 2 | グンマー |  |
| 16 | STB | 1 | Panasonic | MJからパナさんに連絡 |
| 17 | STB用ディスプレイ | 1 | Panasonic | MJからパナさんに連絡 |
| 18 | Fx0 | 5 | KDDI | MJからKDDIさんに連絡 |
| 51 | 充電器 | 1 | Uemmra3 | 5ポートタイプ |
| 52 | テープルタップ、延長コード類 | 約5 | Uemmra3 |  |
| 53 | 3Dプリンターのミニフォクすけ | 2？ | Uemmra3 | すみともさんにもらったやつ |
| 54 | アイロンビーズ製のフォクすけ | 1 | Uemmra3 |  |

**Comment by chikoski** [comment]
1の紙袋に関しては会場で配布があるのでなくても良いでしょう。
2のチラシは配布してもらうように手配します。

あと、タッチ＆トライをしてもらって、その感想をもらいたいので
感想を書いてもらうためのポストイット、回収用の看板とイーゼル、ペンなどを持っていきます。

**Comment by gurezo** [comment]
OSC北海道と同じサイズの奴ですね！
No.9のイーゼルは薄い本用です。

**Comment by Uemmra3** [comment]
にぎやかしとして、アイロンビーズ製のフォクすけと、すみともさんにもらってた3Dプリンター製のフォクすけを持参します。

**Comment by gurezo** [comment]
:+1: 
ところで、STB手配はオッケーですか？？？
それとブースに展示できるスペースがあるかどうか？？？

**Comment by chikoski** [comment]
あと、荷物の送付先の情報をください！＞ @Uemmra3 さん

**Comment by Uemmra3** [comment]
STB手配はもう遅いのかもしれませんが、できればラッキーくらいの気持ちで。
展示スペースについては、佐川さんにご協力頂ければ確保できるのではないかとー。

**Comment by Uemmra3** [comment]
@chikoski さんへ
【到着日・時間】 日付・時間指定厳守！
8月21 日 (金) 9:00～15:00日時指定のこと
【送付先】
住所：〒690-0003島根県松江市朝日町 478-18松江テルサ別館2F
株式会社ネットワーク応用通信研究所内
　宛名：しまねOSS協議会 行
　電話： 0852-28-9298
　備考記入例：「出展団体名」「OSC展示ブース用」「OSC全員配布用」等

**Comment by chikoski** [comment]
To Do：24 or 25 着になるように Fx0 を返送すること。

**Comment by chikoski** [comment]
機材発送しました。

**Comment by Uemmra3** [comment]
OSC島根を閉じます。お疲れ様でした！
