### ISSUE TITLE
【Developers Summit 2016】オフィシャルコミュニティ参加

### ISSUE THREAD

**Issue by MSakamaki** [fxosorg/events#23]
2016-02-18(木) / 19(金) 開催

[Googleぐるーぷ](https://groups.google.com/forum/#!topic/firefoxos-staff/U5ZrJSaLzQ8)

**Comment by MSakamaki** [comment]
今日の夜もうしこみます。
問題有りそうだったら一言ください。

> デブサミに期待すること

だれか考えてください・・・(特に誰も意見言わなければ「なし」で出します)

> 100人以上の会員にメルマガを発行している

Facebookグループをメルマガ扱いとしてYesにしときます。

> 必須 Blog や掲示板、SNS、ミニBlogで、情報を発信している

Facebookグループを(ry

> 必須 コミュニティLT大会への参加を希望しますか？

Yesで申請しときます。

> 必須 オープンジャムへの参加を希望しますか？

人数足りないのでNoにしときます。

**Comment by dynamis** [comment]
期待すること:
ガンガン未来のWeb技術を！

**Comment by MSakamaki** [comment]
:+1:

**Comment by MSakamaki** [comment]
あ、そういえばFirefoxOS関係ないですけど、[MozVR](http://mozvr.com/)を展示したい（個人的欲望）

**Comment by dynamis** [comment]
オキュラスはあるしデモアプリはGithubにあるのでそれも展示すればよいかと。

**Comment by dynamis** [comment]
カードボートとかあるならNexus5にFxOSいれてVRコンテンツも出来るのでは

**Comment by masap** [comment]
WebVR + Oculus +RICOH Theta で手元で動いてるけど、お手伝いできるかは微妙。

WebVR は CPU リソースを食うのでスマホ等で動かすのはきついかも知れません。

**Comment by MSakamaki** [comment]
@masap 
情報ありがとうございます！

一応自前のOculusがあるのと、まだ２ヶ月あるので、
とりあえず間に合えば、最低限動く物を用意しとこうかなと思ってます。

> RICOH Theta

おお、360カメラの発想はなかったので遊んでみます。
色々と時間みて出来そうな事探してみます。

**Comment by dynamis** [comment]
RICOH Theta S ぽちったので必要な場合は貸せます。
18 日は講演で参加することになりそうですがその場合、講演後はブース出展も手伝います

**Comment by MSakamaki** [comment]
デブサミの方から連絡がきたので展開します。

---

Firefox OS コミュニティー
酒巻瑞穂 様

このたびは、オフィシャルコミュニティへのご応募ありがとうございました。
Developers Summit 運営事務局の伊藤でございます。

ぜひ、デブサミ2016のオフィシャルコミュニティにご参加ください！
簡単ですはございますが、現時点でのお願いと今後の進め方について、
ご案内いたします。

＝＝＝＝＝＝＝＝＝＝＝＝＝
＝ ロゴ
＝＝＝＝＝＝＝＝＝＝＝＝＝
本サイト(12月24日公開予定)に掲載させていただくロゴをご提出ください。
こちらのメールへ添付して返信をお願いいたします。

※申込時に、「前回ロゴ流用」「ロゴのリンク先」を記載いただいた方は、提出不要でございます。
ロゴ提出締切：【12月22日(火)】

＝＝＝＝＝＝＝＝＝＝＝＝＝
＝ 今後の流れ
＝＝＝＝＝＝＝＝＝＝＝＝＝
ブース、LT、オープンジャムに関しましては、ご希望通り参加可能でございます。

・留意事項
ブース：2団体で一つのテーブルをご利用いただきます。各団体のコマ割は後日ご案内いたします。
LT:持ち時間3分30秒の予定です。各団体の登壇順は後日ご案内いたします。
オープンジャム：30分枠です。各団体の時間割は後日ご案内いたします。

上記、時間割登壇順などの詳細は1月中旬にご案内をいたします。

引き続き、何卒よろしくお願いいたします。

**Comment by MSakamaki** [comment]
@dynamis 
と言う事で、デブサミで掲載して頂くロゴはどうしましょう？

**Comment by dynamis** [comment]
イベント系の掲載ロゴは場面に応じてこのあたりを送る感じです

https://www.mozilla.org/en-US/styleguide/identity/firefoxos/branding/
https://www.mozilla.org/en-US/styleguide/identity/firefoxos/community/

展示内容候補はざっと思いつく感じで
- VIERA TV (WebIDE でアプリインストールデモ)
  - https://developer.mozilla.org/ja/Firefox_OS/TVs_connected_devices/How_to_connect_WebIDE_to_TV_%28VIErA%29
- Nexus などのスマホへのポーティング
  - https://firefoxos.mozilla.community/devices/
- CHIRIMEN
  - PCSS とか簡単なセンサー類の動作デモ
- それらの相互接続連携？
- WebVR
  - Oculus Rift x Firefox http://mozvr.com/
  - A-Frame https://aframe.io/
- そのたいろいろ

どれやります？VIERA については必要なら貸し出しリクエストに少し時間がかかるので早めに

**Comment by MSakamaki** [comment]
@dynamis 
VIERA TVとCHIRIMENの貸し出しをお願いしたいです。(mozVRは余裕があれば)
とりあえずは１月９日に @gurezo  さんとmozillaにお邪魔するので、そこで軽い打ち合わせ何ど出来ればと考えてます。
あとは、それとは別の日に当日のデモを練習させて貰うため、mozillaさんにちょくちょくお邪魔させてもらえればと。

**Comment by MSakamaki** [comment]
[デブサミページ](http://event.shoeisha.jp/devsumi/20160218/community)にのりました。

**Comment by gurezo** [comment]
:+1:

**Comment by dynamis** [comment]
@MSakamaki @gurezo 応答できて無くてゴメンナサイ。

VIERA 貸し出し申請中、確定したらお知らせします。展示用に使えそうなコンテンツというか Web サービスを CES で聞き取ってきたのでその辺現行 VIERA で問題なく動くか試して連絡します。

CHRIMEN の貸し出しは問題ありません。周辺で接続するモノとかは 1 月におさわりして用意済みという事かと思ってますが大丈夫ですか？

**Comment by MSakamaki** [comment]
@dynamis 

> VIERA 貸し出し申請中、

ありがとうございます！

> CHRIMEN の貸し出しは問題ありません。周辺で接続するモノとかは 1 月におさわりして用意済みという事かと思ってますが大丈夫ですか？

はい大丈夫です、ココの所土日に毎日お邪魔させてもらいかなりノウハウ得る事ができました。

**Comment by dynamis** [comment]
memo: 展示、ブース、テレビについて:
http://event.shoeisha.jp/devsumi/20160218/commu
http://event.shoeisha.jp/static/images/event/418/images/devsumi2016commu_ExhibitorTerms.pdf
http://panasonic.jp/viera/p-db/TH-55CX800N_spec.html

**Comment by dynamis** [comment]
おっと、展示ブースが実は机半分でした。事務局から酒巻さん宛に来ていた回答:

> テレビ展示の件、回答いたします。
> 
> > TV用のアンテナ線は確保可能でしょうか？
> > ＴＶ用アンテナはございませんでした。
> > 
> > 無理な場合室内アンテナを持ち込んでの使用は可能でしょうか？
> > 室内用アンテナの持込みは問題ございませんが、
> > 受信状況を一度、確認頂いた方が良いかもしれません。
> > 直前ですが、2/17（水）であれば、10時～確認可能でございます。
> > それ以前ですと、会場に都度お部屋の空き状況の確認が必要となります。
> 
> なお、展示スペースにつきましては、他の団体と1800mmのテーブルを分け合う形になります。
> テレビの大きさや音量など問題ないでしょうか？
> 
> > また、インターネットに繋がるネットワーク回線の確保は出来るでしょうか？(有線 or 無線どちらか)
> > 無線です。

机半分だと 40 インチでちょうどギリギリサイズです。どうしましょうか？

会場図はこちらで、codeseek たつごろうさんとご一緒になるようです
http://event.shoeisha.jp/static/images/event/418/images/kaijyozu2016.pdf
http://dp28024207.lolipop.jp/other/tatsugoro.htm

**Comment by dynamis** [comment]
DONE.
