### ISSUE TITLE
[3/12] ABC 2016s

### ISSUE THREAD

**Issue by dynamis** [fxosorg/events#25]
ABC 2016s に参加しましょうか。一般一時申し込みは金曜 (2/5) が締め切りの様子:

http://abc.android-group.jp/2016s/

Mozilla としては Android での Web アプリの作り方として最近推してる Progressive Web Apps の説明をする講演を申し込み予定。

**Comment by mhidaka** [comment]
（僕も展示申し込んだので）あわせてやっておきましょうか。

**Comment by dynamis** [comment]
わーいそれ嬉しい。(講演は自分で申し込まなきゃですね…)

きっと誰か来てくれると思うけど誰もいなければ私講演と一緒に頑張るぜモードかな。

**Comment by mhidaka** [comment]
Firefox OSの最新情報をお伝えします。CHIRIMENなど搭載端末の展示や、Connected Devicesへのアプローチ、Web技術によるモバイルアプリケーション開発などの展示を予定しています。

で送信。返事もらい次第、このIssueで連絡しますね。

**Comment by dynamis** [comment]
ありがとうございます。CD へのアプローチはまだ話せるネタが少ないけどゼロではないしそんな感じで大丈夫かと思います。

講演の方は Progressive Web Apps の紹介で申し込みました。
ちょっとスマホでドタバタ入力して記載内容メモってなかったゴメンナサイ。返答来たりなんかし次第 Update します。

**Comment by mhidaka** [comment]
やべぇ。放置してた。転送します

```
FirefoxOSコミュニティ　日高　様


いつも大変お世話になっております。
ABC 2016 Spring バザール担当の鈴木です。

この度はAndroid Bazaar and Conference 2016 Springへの
バザール出展へご応募いただきまして誠にありがとうございました。

選考の結果、貴社・貴団体の出展を採択することと決定いたしましたのでご連絡申し上げます。
つきましては、出展へのご準備を進めていただけますよう、よろしくお願い申し上げます。
なお詳しい出展場所やブース開設準備時刻等につきましては、別途ご連絡いたします。


<ブースについて>
1.各ブースに割り当てられる什器の 上限については、以下のようにいたします。
　ゴールド会員・シルバー会員：机× 2 、椅子× 4 、パーティション
　その他（一般・コミュニティ etc..）：机× 1 、椅子× 2

机のサイズは 180cm×45cm、パーティションの高さは210cmを予定しています。
電源を多く使用する場合は念のため2~3m程の延長コード等をご用意する事をおすすめ致します。


<注意事項とお願い事項>
1.物販について
今回のバザールは物販が可能です。（飲食物はすべてお断りさせていただきます）
なお、金銭のトラブルや盗難等はABC実行委員会、日本Androidの会では一切責任を持ちません。

2.荷物の受取・出荷について
会場側で事前受け取り・出荷ができるよう調整中です。
後日改めて詳細をご連絡いたします。

バザール終了後の荷物の出荷については別途ご案内いたします。
元払いでの出荷に関してはお手数ですが会場近くのコンビニエンスストアなどをご利用ください。

3.駐車場について
お車を使っての荷物の搬入出についてはご希望の方のみ受付をいたしますので別途ご連絡ください。なお、搬入口に横付けできる車の数に限りがあるため、指定の時間に搬入を行なって頂く流れになります。
会場には駐車場はございません。付近のパーキングなどをご利用ください。

4.荷物置場について
出展者様同士の共有スペースとなるため、お荷物は各自ブースでの管理をお願いします。

5.更衣室について
ご用意しておりません。

6.バザール会場の無線LANについて
ご用意しておりません。
また、バザール会場は屋内ですが、ご利用のキャリア・場所によっては電波の入りにくいところがございます。


以上、何かご不明な点やご相談がありましたら、
ABC 2016 Spring実行委員会までご連絡いただけますよう、お願い申し上げます。
```

**Comment by dynamis** [comment]
講演快諾については FB メッセンジャーの闇に消えていた事が判明した (絶対に気付かない友達登録前のメッセージが先週来てた) が連絡が取れたので下記で。講演タイトルとかは今日中に書いて送る。

日時：3月12日(土)　14:00 - 14:45　
場所：青山学院大学　青山キャンパス　17号館　4F　17406教室

**Comment by mhidaka** [comment]
Facebookの闇だ。

**Comment by mhidaka** [comment]
```
★今回展示頂くブース番号は、「２０」です。
青山学院大学　１７号館　４階　17411教室

机のサイズは 195cm×45cm、パーティションの高さは180cmを予定しています。
注意：今回は電源を増強する事が出来ないため、
なるべく机１本に対し、1Aに収まるようにしてください。
電源の数を多く使用する場合は念のため2~3m程の延長コード等をご用意する事をおすすめ致します。
```

**Comment by dynamis** [comment]
こちらの Update ありませんか？

> 2.荷物の受取・出荷について
> 会場側で事前受け取り・出荷ができるよう調整中です。
> 後日改めて詳細をご連絡いたします。

**Comment by mhidaka** [comment]
秘密裏にDMおくっておきました。あ、ごめんなさいふつうのフェイスブックメッセンジャーです。個人情報ｐっぽいものがみえたのでそちらに。

**Comment by dynamis** [comment]
あ、なるほどすれ違いましたね。ありがとう！

**Comment by dynamis** [comment]
Panasonic さんに TH-55CX800N を貸し出して頂けることになりました。組み立て・梱包などはコミュニティメンバーで行い、引き取り便はサイズが大きいので専用に以下の情報で手配しています:

引き取り便の手配情報:

> 日時: 3/12 (土) 18:00
> 〒150-8366 東京都渋谷区渋谷4-4-25 青山学院大学 青山キャンパス 17号館
> バザール会場、Firefox OS コミュニティブース
> 当日連絡先: 090-***_-**_\* (浅井)

**Comment by mhidaka** [comment]
:+1:

**Comment by dynamis** [comment]
VIERA 向けの展示メモ: https://github.com/fxosorg/events/wiki/demo-with-VIERA

**Comment by gurezo** [comment]
グンマーお手伝い予定です

**Comment by mhidaka** [comment]
わいわい。

**Comment by dynamis** [comment]
展示アイテム:
- [x] VIERA (借り物)
- [x] フォクすけ x 2 (展示のヘルプ)
- [x] CHIRIMEN x 2
- [x] 小型ディスプレイ、USB ハブ、WiFiドングル、マウス
- [x] 距離センサー、スルーホール用テストワイヤ
- [x] てくぶ本 各 1

配りもの:
- [x] Firefox ステッカー x 400
- [x] Android Firefox ステッカー x 200
- [x] MDN チラシ x 1xx
- [x] iOS Firefox チラシ x 200
- [x] Firefox 入れ墨シール x 4 セット (枚数未確認)

講演配りもの:
- [x] Firefox ステッカー x 100
- [x] iOS Firefox チラシ x 100
- [x] アンケート用紙 x 100 + えんぴつ適量

**Comment by dynamis** [comment]
DONE. ありがとうございましたー。
