### ISSUE TITLE
地デジアンテナをどうにかする

### ISSUE THREAD

**Issue by dynamis** [fxosorg/events#4]
配線許可もらって引いてくる？
室内や車用のアンテナの場合は受信できるかの確認も

**Comment by mhidaka** [comment]
そのあたりは運営にきいてみますね

**Comment by Makoto1987** [comment]
・会場にTVアンテナの端子があればそこから配線するのが一番。
・端子がなければ簡易アンテナ。
→ こんなの。 http://ctlg.panasonic.com/jp/tv-theater/tv-acc/tuner-antenna/lineup.html
(これはフラットだけど八木アンテナ並みに高性能)
・NHKと民放各局を受信するにはスカイツリー方向にアンテナを向ける必要があり。
→ 会場の窓とか入口の方角次第。
・tvkの送信所は近いので、室内でも入るかなあ。入るといいなあ。

［Dpa］放送エリアのめやす http://dpa-tv-area.jp/map/14

**Comment by mhidaka** [comment]
実際どうにかなってたのはすごい。

**Comment by Makoto1987** [comment]
Closedになってるけど、今回の経験則を書いておこう。
平面アンテナなら半値角が広いので、室内でも高さを稼げば方向はアバウトでも結構行ける。
もし次回があるなら、高い位置に固定できるスタンドがあるといいかも。

**Comment by mhidaka** [comment]
:+1:
