### ISSUE TITLE
当日スタッフ

### ISSUE THREAD

**Issue by dynamis** [fxosorg/events#6]
誰が行けますか？
と念のためIssueに書いておく

**Comment by mhidaka** [comment]
イケる人挙手しときましょう。
ﾉｼ（自分のバザールがうかったらそっちにいる可能性びれぞん）

**Comment by aoitan** [comment]
ほぼ確いけるﾉ

**Comment by mhidaka** [comment]
assigneeの殴り合いウケる

**Comment by Makoto1987** [comment]
たぶんノ

**Comment by mhidaka** [comment]
:+1:

**Comment by flatbird** [comment]
いけます！

**Comment by mhidaka** [comment]
やったぁ😆

**Comment by gurezo** [comment]
今北産業
お邪魔でなければ、お手伝いします！ノ

**Comment by mhidaka** [comment]
ﾖﾛｼｸｵﾅｼｬｽ！

**Comment by namaranran** [comment]
書けてなかった
ノシ

**Comment by dynamis** [comment]
もろもろあって行きます。(・・)/
ずっとブースに常駐はできないと思うのですが可能な範囲でいます。

**Comment by dynamis** [comment]
一応多めに年代物 T シャツを 12 まい手配しました。(ladies M x 2 含む)
各自持っている好きな T シャツ持ってきてきてくれても問題ありません。

**Comment by mhidaka** [comment]
Thank you so much！！
