### ISSUE TITLE
The FoxとFirefoxのロゴのベクター(白黒)が欲しい

### ISSUE THREAD

**Issue by meco300** [fxosorg/events#7]
The FoxとFirefoxのロゴの白黒ベクター(家紋的な感じで)を作りましたが、版権的にダメですよね。
・もじらさんに白黒のベクターありますか。
・ない場合、作ってもらえますか。
・それでもダメなら、こちらで作ったやつ使えますか。
(ここまで全てダメだと企画が破綻)

**Comment by mhidaka** [comment]
#5 関連

https://www.mozilla.org/en-US/styleguide/identity/firefoxos/community/ The Foxのブランドデザイン（コミュニティ甩）
https://www.mozilla.org/en-US/styleguide/identity/firefoxos/branding/ ロゴブランディング

これのEPSを使ってる感じなんです？ @meco300 氏

**Comment by meco300** [comment]
@mhidaka 氏
白黒1色刷りにしたかったので
・the foxは公式絵をアウトライン化して白黒のベクターに
・firefoxロゴはフリー素材で1色ベクターになっているものがあったので、それを。

(ちなみに、1色刷りの染めにするとにじみが出てあんまり詳細なところまで再現できません)

**Comment by mhidaka** [comment]
きびしそう…（こなみかん）

**Comment by dynamis** [comment]
カラーのベクターはあるけど白黒ベクターはない＆つくれません (技術的には作れるけど)

勝手に白黒にしたバージョンを使って良いかという件については少なくともスタイルガイドの文面的には You maynot: change the color of the white pencil-sketch line art or fill in the fox images with any color に引っかかると思います。

**Comment by meco300** [comment]
では、破綻ということで…
