### ISSUE TITLE
2015/07/04 HTML5 Conference 2015 in 鹿児島に展示ブース出展

### ISSUE THREAD

**Issue by dynamis** [fxosorg/events#9]
ブース出展して欲しいというリクエスト by 主催者

http://kagoshima.html5j.org/html5conference.2015/#session

**Comment by meco300** [comment]
ノ

**Comment by albatrosary** [comment]
m(__)m

**Comment by meco300** [comment]
ブース情報 from 佐川さん
・50人部屋を利用
・ブースは3人がけ長机1個分
・電源あり
・Wifiは自前で用意
・パンフレット等の配布は可
・機材の送付先：
〒890-­0064 鹿児島市鴨池新町5−1 鴨池ACアネックス
株式会社富士通鹿児島インフォネット ソリューション営業部 大川

@albatrosary 
詳細情報ください。
・壁が使える場所は確保できたでしょうか。
・ディスプレイの借用は可能ですか。
・機材送付の期間はいつからいつまででしょうか。

@dynamis 
下記ご用意願います。
・各種チラシ
・配布可能なノベルティ(シールとか)
・Fx0(3台くらい)
・Frame(2台くらい)
・ちりめん(1台)
　・端末に繋げるワイヤーみたいなやつ(盗難防止)
　・端末充電用のケーブル・USBとコンセント繋げるヤツ
・壁が利用できる場合はポスターなど壁に貼れるもの
・Wifiルータ(展示内容によっては不要)
・机にしく布
・本やチラシを立てかけるやつ
・FxOS本(てくぶの同人誌含め)
・フォクすけ(1匹)
(・レッサーパンダの着ぐるみ)

mecoの方で用意するものは少ないので
@dynamis 側の機材だけ詰めて送付してしまってください。

@meco300
・Fx0に何かアプリ入れておく
・ディスプレイを借りられる場合は何か展示できそうなものを考える
現状ではチラシ配って端末とかをおさわりしてもらう、という雰囲気なのですが
もう少し何か体験できる展示ができないか考えてみます。

**Comment by meco300** [comment]
@dynamis 
主催の人に聞きました。
・壁もしくは窓(ブラインド)があるので、そこに養生テープでなにか貼るのはアリ
・13インチのディスプレイだったら提供可
・24インチもあるが、できれば小さい方がよい

だそうです。
もしディスプレイするなら、梶井さんのFirefox OS ガチャを展示できるといいなと思っていますが、いかがでしょうか。OWBなんですけど。

**Comment by dynamis** [comment]
以下の荷物を送付予定 (Fx0 は手持ちのモノも持ってきてください):

Fx0 2
Flame 2
OWB  1
新FirefoxOSパンフ　200
FX０チラシ　200
Panasonic ビエラカタログ　100
新アプリ開発者向けフライヤー　200
Firefox OS 本 5 種 (コミケ本 3 種含む)
フォクすけぬいぐるみ（小）1
Touch ＆ Try パネル（A1パネル）
スマホスタンド  5
イーゼル １本
付箋束　８束
サインペン １セット
新Mozillaステッカー　200
文房具一式　
電源TAP　2本
USB 6口充電器 １
USB キーボード＆マウス＆ハブ 1 式
HDMI ケーブル 1 本
バミテ　1個
返送用着払い用紙
Firefox OS紙袋　３枚ほど
